name: motion_core
description: "A new Flutter plugin project."
version: 0.0.1
homepage: https://github.com/miracle101000/flutter_native_ml 

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  plugin:
    platforms:
      android:
        package: com.example.motion_core
        pluginClass: MotionCorePlugin
      ios:
        pluginClass: MotionCorePlugin
